map <F1> j0.
map <F2> n.
map <F3> nn.
map <F4> j$.
map <F5> r0jr1jr2jr3jr4jr5jr6jr7jr8jr9j
map <F6> .j.j.j.j.j.j.j.j.j.j
map <F7> r0jr1jr2jr3jr4jr5jr6jr7jr8jr9jrajrbjrcjrdjrejrfj
map <F8> .j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j

set tabstop=2         " <TAB> four spaces
set shiftwidth=2      " Shift width four spaces (for auto indent)
set noautoindent      " Turn off autoindent by default
"set smartindent       " Use smart indent instead
set incsearch         " Use incremental searches (cool)
set backspace=2       " Set backspace mode to allow backspacing in insert mode
set ruler             " Show position of cursor in status line
set showmatch         " Show matching parens/braces when writing code
set wh=55             " Minimum window height
set textwidth=78      " Maximum line width when writing comments
set history=1000

" Speed up response to ESC key
set notimeout
set ttimeout
set timeoutlen=100

" Make completion more like bash
"set wildmode=longest,list

" Cure hangs during compiles?
"  set swapsync=

" Disable auto-commenting of // in C/C++
"au FileType verilog,c,cpp setlocal comments-=://
set formatoptions-=cro

set tw=0

set nocompatible
filetype plugin on
syntax on
runtime macros/matchit.vim

set spelllang=en
set spellfile=$HOME/Development/gitbox/devenv/spell-en.utf-8.add

autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

autocmd BufNewFile,BufRead *.jsn set ft=javascript
" Highlight trailing whitespace
"hi TrailingSpace ctermbg=1
"au filetype c,cpp,python match TrailingSpace "\s\+\n"

augroup filetype
  au! BufRead,BufNewFile *.ll set filetype=llvm
augroup END

augroup filetype
  au! BufRead,BufNewFile *.td set filetype=tablegen
augroup END

augroup filetype
  au! BufRead,BufNewFile *Makefile* set filetype=make
augroup END

augroup filetypedetect
  au! BufRead,BufNewFile *.asp,*.ash,*.ah set filetype=aspen
augroup END

"augroup textSpell
"  au! FileType text setlocal spell
"augroup END

if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
endif
